# Generated by Django 3.2.8 on 2021-11-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_galeri', models.CharField(max_length=30)),
                ('sampul_galeri', models.ImageField(blank=True, null=True, upload_to='images/galeri/')),
                ('keterangan_galeri', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GambarGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gambar', models.CharField(max_length=30)),
                ('gambar_galeri', models.ImageField(blank=True, null=True, upload_to='images/galeri/')),
                ('default', models.BooleanField(default=False)),
                ('nama_galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galeri.galeri')),
            ],
        ),
    ]
