# Generated by Django 3.2.8 on 2021-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_delete_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
