# Generated by Django 3.2.8 on 2021-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_auto_20211128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'guru'), (2, 'siswa')], null=True),
        ),
    ]
