# Generated by Django 3.2.8 on 2021-10-31 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0002_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id_guru', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guru.customuser')),
                ('nip', models.CharField(max_length=30, null=True)),
                ('tempat_lahir', models.CharField(max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('mapel_id', models.IntegerField(null=True)),
                ('no_telp', models.IntegerField(null=True)),
                ('pendidikan', models.CharField(max_length=50, null=True)),
                ('foto_guru', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
