# Generated by Django 3.2.8 on 2021-10-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='id_guru',
            new_name='email_guru',
        ),
    ]
