# Generated by Django 3.2.8 on 2021-11-21 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0002_rename_id_guru_profil_email_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email_guru',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
