# Generated by Django 3.2.8 on 2021-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_alter_profil_email_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='foto_guru',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
