# Generated by Django 3.2.8 on 2021-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_profil_foto_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nama_guru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
