# Generated by Django 3.2.8 on 2021-11-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_customuser_user_type'),
        ('profil', '0005_profil_nama_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSiswa',
            fields=[
                ('email_siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_siswa', serialize=False, to='guru.customuser')),
                ('nama_siswa', models.CharField(max_length=30, null=True)),
                ('nisn', models.CharField(max_length=30, null=True)),
                ('tempat_lahir', models.CharField(max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jurusan', models.IntegerField(null=True)),
                ('no_telp', models.IntegerField(null=True)),
                ('kelas', models.CharField(max_length=50, null=True)),
                ('foto_siswa', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
