# Generated by Django 3.2.8 on 2021-11-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
        ('profil', '0006_profilsiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='mapel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajar', to='mapel.matapelajaran'),
        ),
    ]
