# Generated by Django 3.2.8 on 2021-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_profil_mapel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='no_telp',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='no_telp',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
