# Generated by Django 3.2.8 on 2021-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20211201_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsiswa',
            name='jurusan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
