# Generated by Django 3.2.8 on 2021-11-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Berita',
            new_name='Pengumuman',
        ),
        migrations.RenameField(
            model_name='pengumuman',
            old_name='isi_berita',
            new_name='isi_pengumuman',
        ),
        migrations.RenameField(
            model_name='pengumuman',
            old_name='tanggal_berita',
            new_name='tanggal_pengumuman',
        ),
    ]
